# Generated by Django 4.2.5 on 2023-12-23 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id_car', models.AutoField(db_column='ID_car', primary_key=True, serialize=False)),
                ('model', models.TextField(db_column='Model')),
                ('color_auto', models.TextField(blank=True, db_column='Color_auto', null=True)),
                ('rented', models.TextField(blank=True, db_column='Rented', null=True)),
                ('reg_number_auto', models.IntegerField(db_column='Reg_number_auto')),
            ],
            options={
                'db_table': 'Cars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id_instructor', models.OneToOneField(db_column='ID_instructor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.users')),
                ('rating', models.IntegerField(blank=True, db_column='Rating', null=True)),
            ],
            options={
                'db_table': 'Instructors',
                'managed': False,
            },
        ),
    ]
